import { Router } from 'express';
import auth from './auth.routes.js';
import users from './user.routes.js';
import students from './student.routes.js';
import faculty from './faculty.routes.js';
import academic from './academic.routes.js';
import attendance from './attendance.routes.js';
import marks from './marks.routes.js';
import schedule from './schedule.routes.js';
import assignments from './assignment.routes.js';
import notices from './notice.routes.js';
import notifications from './notification.routes.js';
import materials from './material.routes.js';
import calendar from './calendar.routes.js';
import documents from './document.routes.js';
import complaints from './complaint.routes.js';
import achievements from './achievement.routes.js';
import fees from './fee.routes.js';
import placements from './placement.routes.js';
import library from './library.routes.js';
import reports from './report.routes.js';
import importer from './import.routes.js';
import dashboard from './dashboard.routes.js';
import { settingsRouter, auditRouter } from './settings.routes.js';

const r = Router();
r.use('/auth', auth);
r.use('/users', users);
r.use('/students', students);
r.use('/faculty', faculty);
r.use('/attendance', attendance);
r.use('/marks', marks);
r.use('/assignments', assignments);
r.use('/notices', notices);
r.use('/notifications', notifications);
r.use('/materials', materials);
r.use('/calendar', calendar);
r.use('/documents', documents);
r.use('/complaints', complaints);
r.use('/achievements', achievements);
r.use('/fees', fees);
r.use('/placements', placements);
r.use('/library', library);
r.use('/reports', reports);
r.use('/import', importer);
r.use('/dashboard', dashboard);
r.use('/settings', settingsRouter);
r.use('/audit-logs', auditRouter);
// academic structure (/departments, /programs, /subjects, ...) and schedule (/exams, /timetable)
r.use('/', academic);
r.use('/', schedule);

export default r;
